# -*- coding: utf-8 -*-
"""Drug_Decision Tree_Athul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vPb2YBOAtpe1GDA88s-odHbWxRcwsLFX
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
import numpy as np

#Splitting the dataset into train and test
from sklearn.model_selection import train_test_split


#import the decisiontree classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report

# for pre-processing
from sklearn import preprocessing

#import the datasets
df = pd.read_csv("/content/drug200.csv")

df.head()

df.dtypes

df.describe()

df.info

df.shape

df.isnull().sum()

label_encoder = preprocessing.LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['BP'] = label_encoder.fit_transform(df['BP'])
df['Drug'] = label_encoder.fit_transform(df['Drug'])

df

x = df.iloc[:,0:5]
y = df.iloc[:,5]

x

y

# Splitting the dataset into train and test

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=44)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

x_test

y_test

# Building Decision Tree Classifier using Entropy as a Criterion

model =  DecisionTreeClassifier(criterion='entropy',max_depth = 4)

model.fit(x_train,y_train)

# PLot the decsion Tree

tree.plot_tree(model)

fn = ['Age','Sex','BP','Cholesterol','Na_to_K']
cn = ['drugA','drugB','drugC','drugX','drugY']
fig,axes = plt.subplots(nrows=1, ncols=1, figsize=(2,2), dpi=400)
tree.plot_tree(model,feature_names=fn,class_names = cn, filled=True)

preds = model.predict(x_test)

pd.Series(preds).value_counts()

preds

y_test

# Crosstab : Way to understand the two way table between predicted vs actual

pd.crosstab(y_test,preds)

# Accuracy of the above model

np.mean(preds==y_test)

x_test['preds']=preds

x_test['y_test']=y_test

x_test

